name: Create AWS RDS SQL Server Instance

on:
  workflow_dispatch: # Manual trigger for time being

jobs:
  create-rds:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Check if RDS instance exists
        id: check-db
        run: |
          if aws rds describe-db-instances --db-instance-identifier ${{ vars.DB_INSTANCE_IDENTIFIER }} > /dev/null 2>&1; then
            echo "DB_EXISTS=true" >> $GITHUB_ENV
          else
            echo "DB_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create RDS SQL Server instance if not exists
        if: env.DB_EXISTS == 'false'
        run: |
          aws rds create-db-instance \
            --db-instance-identifier ${{ vars.DB_INSTANCE_IDENTIFIER }} \
            --db-instance-class ${{ vars.DB_INSTANCE_CLASS }} \
            --engine ${{ vars.DB_ENGINE }} \
            --allocated-storage ${{ vars.DB_STORAGE }} \
            --master-username ${{ vars.DB_MASTER_USERNAME }} \
            --master-user-password ${{ secrets.DB_MASTER_PASSWORD }} \
            --backup-retention-period 7 \
            --publicly-accessible \
            --no-multi-az \
            --storage-encrypted
